embed_dim: 128
action_dim: 2
in_c: 2
epochs: 20
batch_size: 1536
learning_rate: 0.0015
model_type: 'ActionRegularizationJEPA'
data_path: '/scratch/DL24FA/train'

# action regularization
action_reg_hidden_dim: 32
lambda_reg: 0.2

vicreg_loss:
  lambda_invariance: 1.0
  mu_variance: 75.0
  nu_covariance: 25.0