action_dim: 2
action_reg_hidden_dim: 32
batch_size: 1024
data_path: /scratch/DL24FA/train
embed_dim: 128
epochs: 20
in_c: 2
lambda_reg: 1
learning_rate: 0.001
model_type: ActionRegularizationJEPA
vicreg_loss:
  lambda_invariance: 1
  mu_variance: 25
  nu_covariance: 25
