embed_dim: 289
action_dim: 2
in_c: 2
out_c: 64
epochs: 20
batch_size: 512
learning_rate: 0.00015
model_type: 'ActionRegularizationJEPA2DFlexibleEncoder'
data_path: '/scratch/DL24FA/train'
optimizer_type: 'adam'
scheduler_type: 'onecycle'

# action regularization
action_reg_hidden_dim: 32
lambda_reg: 0

vicreg_loss:
  lambda_invariance: 1
  mu_variance: 25
  nu_covariance: 1

encoder_backbone: resnet18.a1_in1k