embed_dim: 256
action_dim: 2
in_c: 2
epochs: 20
batch_size: 1024
learning_rate: 0.001
model_type: 'JEPA'
data_path: '/scratch/DL24FA/train'

vicreg_loss:
  lambda_invariance: 1.0
  mu_variance: 100.0
  nu_covariance: 25.0